pipeline:
  identifier: Build_jimsheldon_nextjs_docker_1704403654286
  name: Build nextjs-docker
  orgIdentifier: default
  projectIdentifier: jim_sheldon_dec7
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1701977172921
        repoName: jimsheldon/nextjs-docker
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Docker Build
                  identifier: Docker_Build
                  spec:
                    connectorRef: account.harnessImage
                    repo: example/repo
                    tags:
                      - latest
                    caching: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
        type: CI
        variables:
          - name: PLUGIN_DRY_RUN
            type: String
            description: ""
            required: false
            value: "true"
